### ISSUE TITLE
'Split'-command does not serialize list-style configs correctly 

### ISSUE THREAD

**Issue by earloc** [earloc/hasso#12]
invoke the 'split'-command on the following ```scenes.yaml```-file

```yaml
- id: '123456789'
  name: some_scene_name_1
  entities:
    light.light_1:
      min_mireds: 250
      max_mireds: 454
      brightness: 40
      color_temp: 454
      friendly_name: light 1 friendly name
      supported_features: 35
      state: 'on'
    light.light_2:
      min_mireds: 250
      max_mireds: 454
      brightness: 40
      color_temp: 454
      friendly_name: light 1 friendly name
      supported_features: 35
      state: 'on'
    switch.power_1:
      friendly_name: power 1 friendly name
      state: 'on'
- id: '987654321'
  name: some_scene_name_2
  entities:
    light.light_1:
      min_mireds: 250
      max_mireds: 454
      brightness: 80
      color_temp: 454
      friendly_name: light 1 friendly name
      supported_features: 35
      state: 'on'
    light.light_2:
      min_mireds: 250
      max_mireds: 454
      brightness: 80
      color_temp: 454
      friendly_name: light 1 friendly name
      supported_features: 35
      state: 'on'
    switch.power_1:
      friendly_name: power 1 friendly name
      state: 'off'
```

**expected:**
a file ```scenes/some_scene_name_1.partial.yaml´``` with the folowing content:
```yaml
- id: '123456789'
  name: some_scene_name_1
  entities:
    light.light_1:
      min_mireds: 250
      max_mireds: 454
      brightness: 40
      color_temp: 454
      friendly_name: light 1 friendly name
      supported_features: 35
      state: 'on'
    light.light_2:
      min_mireds: 250
      max_mireds: 454
      brightness: 40
      color_temp: 454
      friendly_name: light 1 friendly name
      supported_features: 35
      state: 'on'
    switch.power_1:
      friendly_name: power 1 friendly name
      state: 'on'
```
**actual:**
a file ```scenes/some_scene_name_1.partial.yaml``` with the following content:
```yaml
some_scene_name_1:
  id: 123456789
  name: some_scene_name_1
  entities:
    light.light_1:
      min_mireds: 250
      max_mireds: 454
      brightness: 40
      color_temp: 454
      friendly_name: light 1 friendly name
      supported_features: 35
      state: on
    light.light_2:
      min_mireds: 250
      max_mireds: 454
      brightness: 40
      color_temp: 454
      friendly_name: light 1 friendly name
      supported_features: 35
      state: on
    switch.power_1:
      friendly_name: power 1 friendly name
      state: on
```
