### ISSUE TITLE
ID-strings not serialized with enclosing SingleQoutes when splitted

### ISSUE THREAD

**Issue by earloc** [earloc/hasso#17]
consider the follwoing ```scenes.yaml```

```yaml
- id: '123456789'
  name: some_scene_name_1
  entities:
    light.light_1:
      state: 'on'
    light.light_2:
      state: 'on'
    switch.power_1:
      friendly_name: power 1 friendly name
      state: 'on'
- id: '987654321'
  name: some_scene_name_2
  entities:
    light.light_1:
      state: 'on'
    light.light_2:
      state: 'on'
    switch.power_1:
      state: 'off'
```

**expected** output (```some_scene_name_1.parial.yaml```):
```yaml
- id: '123456789'
  name: some_scene_name_1
  entities:
    light.light_1:
      state: 'on'
    light.light_2:
      state: 'on'
    switch.power_1:
      friendly_name: power 1 friendly name
      state: 'on'
```

actual output (notice the missing **'s** ):
```yaml
- id: 123456789
  name: some_scene_name_1
  entities:
    light.light_1:
      state: on
    light.light_2:
      state: on
    switch.power_1:
      friendly_name: power 1 friendly name
      state: on
```
