### ISSUE TITLE
"Split" serializes the "after"-field of a time-condition without enclosing SingleQoutes

### ISSUE THREAD

**Issue by earloc** [earloc/hasso#18]
consider the following ```automations.yaml```
```yaml
- id: '123456789'
  ...
  condition:
  - condition: time
    after: '01:00:00'
    before: 02:00:00
- id: '987654321'
  ...
  condition:
  - condition: time
    after: '02:00:00'
    before: 03:00:00
```

**expected** result after split:
```yaml
- id: '123456789'
  ...
  condition:
  - condition: time
    after: '01:00:00'
    before: 02:00:00
```

**actual** result:
```yaml
- id: '123456789'
  ...
  condition:
  - condition: time
    after: 01:00:00
    before: 02:00:00
```

note the missing **SingleQoutes**:
```after: 01:00:00```
instead of 
```after: '01:00:00' ```

**Comment by earloc** [comment]
For whatever reason, HA needs the "after"-field enclosed in **''** when using a fixed value. Unclear to me, what the difference between "after" and "before" is, but "before" works just fine without the enclosed '' (HA itself omit them there, btw.)

To avoid HA choking on this, one could leverage a helper instead the inline fixed value:

```yaml
- id: '123456789'
  ...
  condition:
  - condition: time
    after: input_datetime.some_value
    before: 02:00:00
```
