### ISSUE TITLE
add support for splitting files hierarchical

### ISSUE THREAD

**Issue by earloc** [earloc/hasso#3]
As a hass.io-admin, I want to optionally split the monolithic confiuration files into small files in a hierarchical way, so that I can better browse and edit the various components in e.g. vs-code more easily.

e.g.:

The following contents of  `scripts.yaml`
```yaml
some_script_name_1:
  alias: Some.Script.Name 1
  sequence:
  ...
  mode: restart
some_script_name_2:
  alias: Some.Script.Name 2
  sequence:
  ...
  mode: restart
someother_script_name_3:
  alias: SomeOther.Script.Name 2
  sequence:
  ...
  mode: restart
```

should be exploded/splitted/decomposed into the following folder-structure:

```
./Scripts/Some/Script/Name 1.partial.yaml
./Scripts/Some/Script/Name 2.partial.yaml
./Scripts/SomeOther/Script/Name 3.partial.yaml
```

as opposed to the curent default-structure:

```
./Scripts/Some.Script.Name 1.partial.yaml
./Scripts/Some.Script.Name 2.partial.yaml
./Scripts/SomeOther.Script.Name 3.partial.yaml
```
